using System.Text.Json;
using System.Text.Json.Nodes;
using GenesisMesh;
using Xunit;

namespace GenesisMesh.Sdk.Tests;

/// <summary>
/// Shared conformance suite <c>canonical</c> (v1.2.0), generated by the Python reference
/// (genesismesh/conformance/generate_vectors.py canonical) and copied here unchanged: the field
/// registry of signed records and the fields every verifier refuses.
/// </summary>
public class CanonicalConformanceTests
{
    private static readonly string SuitePath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "canonical.json");
    private static readonly string InteropPath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "interop.json");

    private static JsonElement Suite() => JsonDocument.Parse(File.ReadAllText(SuitePath)).RootElement;

    public static IEnumerable<object[]> VectorIds() =>
        Suite().GetProperty("vectors").EnumerateArray().Select(v => new object[] { v.GetProperty("id").GetString()! });

    [Fact]
    public void EmbedsTheRegistryOfTheSuite()
    {
        var suite = JsonNode.Parse(Suite().GetProperty("registry").GetRawText());
        var embedded = JsonNode.Parse(StrictFields.Registry.GetRawText());
        Assert.True(JsonNode.DeepEquals(suite, embedded),
            "canonical_registry.json differs from the suite: write the suite's registry member to it");
    }

    [Theory]
    [MemberData(nameof(VectorIds))]
    public void ReproducesTheReferenceOutcome(string id)
    {
        var v = Suite().GetProperty("vectors").EnumerateArray().Single(x => x.GetProperty("id").GetString() == id);
        var expected = v.GetProperty("expected");
        switch (v.GetProperty("kind").GetString())
        {
            case "unknown_fields":
                var want = expected.GetProperty("unknown_fields").EnumerateArray().Select(e => e.GetString()!)
                    .OrderBy(s => s, StringComparer.Ordinal).ToList();
                Assert.Equal(want, StrictFields.UnknownFields(v.GetProperty("model").GetString()!, v.GetProperty("record")));
                break;
            case "entry_kind":
                Assert.Equal(expected.GetProperty("known").GetBoolean(),
                    StrictFields.IsKnownEntryKind(v.GetProperty("entry_kind").GetString()!));
                break;
            default:
                Assert.Fail($"unknown kind {v.GetProperty("kind").GetString()}");
                break;
        }
    }

    private static JsonElement Input(string id) =>
        JsonDocument.Parse(File.ReadAllText(InteropPath)).RootElement.GetProperty("vectors").EnumerateArray()
            .Single(v => v.GetProperty("id").GetString() == id).GetProperty("input");

    private static string WithField(JsonElement record, string key)
    {
        var node = JsonNode.Parse(record.GetRawText())!.AsObject();
        node[key] = "x";
        return node.ToJsonString();
    }

    private static List<string> Strings(JsonElement input, string key) =>
        input.GetProperty(key).EnumerateArray().Select(e => e.GetString()!).ToList();

    [Fact]
    public void VerifiersRefuseFieldsTheyDoNotKnow()
    {
        var bd = Input("bd-003");
        var options = new DecisionVerifyOptions
        {
            OperatorPublicKeys = Strings(bd, "operator_public_keys"),
            Now = OfflineVerifier.ParseTimestamp(bd.GetProperty("now").GetString()!),
        };
        Assert.Equal("authorized", OfflineVerifier.VerifyBoundaryDecision(bd.GetProperty("decision").GetRawText(), options).Reason);
        var later = OfflineVerifier.VerifyBoundaryDecision(WithField(bd.GetProperty("decision"), "risk_tier"), options);
        Assert.False(later.Accepted);
        Assert.Equal("unknown_field", later.Reason);

        var policy = WithField(Input("bd-001").GetProperty("expected_policies")[0], "x");
        var withPolicy = new DecisionVerifyOptions
        {
            OperatorPublicKeys = options.OperatorPublicKeys, Now = options.Now, ExpectedPolicies = new[] { policy },
        };
        Assert.Equal("unknown_field", OfflineVerifier.VerifyBoundaryDecision(bd.GetProperty("decision").GetRawText(), withPolicy).Reason);

        var agr = Input("agr-001");
        Assert.Equal("unknown_field", OfflineVerifier.VerifyAgreement(WithField(agr.GetProperty("agreement"), "x"),
            Strings(agr, "offerer_public_keys"), Strings(agr, "responder_public_keys")).Reason);

        var pol = Input("pol-001");
        Assert.False(OfflineVerifier.VerifyDataLicensePolicySignature(WithField(pol.GetProperty("policy"), "x"),
            Strings(pol, "licensor_public_keys")));

        var intent = Input("int-001");
        var r = OfflineVerifier.VerifyDataAccessIntent(WithField(intent.GetProperty("intent"), "x"),
            intent.GetProperty("policy").GetRawText(), Strings(intent, "agent_public_keys"),
            OfflineVerifier.ParseTimestamp(intent.GetProperty("at").GetString()!));
        Assert.False(r.Valid);
        Assert.Equal("intent_exceeds_license", r.ViolationReason);
    }
}
