using System.Text.Json;
using GenesisMesh;
using Xunit;

namespace GenesisMesh.Sdk.Tests;

/// <summary>
/// Shared conformance suite <c>canonical</c> (v1.2.0), generated by the Python reference
/// (genesismesh/conformance/generate_vectors.py canonical) and copied here unchanged: input every
/// implementation reads alike or refuses by reason, and the canonical form of records.
/// </summary>
public class CanonicalSuiteTests
{
    private static readonly string SuitePath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "canonical.json");

    private static JsonElement Suite() => JsonDocument.Parse(File.ReadAllText(SuitePath)).RootElement;

    private static JsonElement Vector(string id) =>
        Suite().GetProperty("vectors").EnumerateArray().Single(x => x.GetProperty("id").GetString() == id);

    public static IEnumerable<object[]> VectorIds() =>
        Suite().GetProperty("vectors").EnumerateArray().Select(v => new object[] { v.GetProperty("id").GetString()! });

    private static List<string> Strings(JsonElement input, string key) =>
        input.GetProperty(key).EnumerateArray().Select(e => e.GetString()!).ToList();

    [Fact]
    public void HasEnoughVectors() => Assert.True(VectorIds().Count() >= 70);

    [Theory]
    [MemberData(nameof(VectorIds))]
    public void ReproducesTheReferenceOutcome(string id)
    {
        var v = Vector(id);
        var expected = v.GetProperty("expected");
        var input = v.GetProperty("input");
        switch (v.GetProperty("kind").GetString())
        {
            case "json":
                string? canonical = null, refused = null;
                try { canonical = Canonical.FromJson(input.GetString()!); }
                catch (StrictJsonException e) { refused = e.Reason; }
                if (expected.TryGetProperty("canonical", out var want)) Assert.Equal(want.GetString(), canonical);
                else Assert.Equal(expected.GetProperty("refused").GetString(), refused);
                break;
            case "timestamp":
                Assert.Equal(expected.GetProperty("canonical").GetBoolean(), StrictFields.CanonicalTimestamp(input.GetString()!));
                break;
            case "verify_decision":
            {
                var r = OfflineVerifier.VerifyBoundaryDecision(input.GetProperty("decision").GetRawText(), new DecisionVerifyOptions
                {
                    OperatorPublicKeys = Strings(input, "operator_public_keys"),
                    Now = OfflineVerifier.ParseTimestamp(input.GetProperty("now").GetString()!),
                });
                Assert.Equal((expected.GetProperty("accepted").GetBoolean(), expected.GetProperty("reason").GetString()), (r.Accepted, r.Reason));
                break;
            }
            case "verify_agreement":
            {
                var r = OfflineVerifier.VerifyAgreement(input.GetProperty("agreement").GetRawText(),
                    Strings(input, "offerer_public_keys"), Strings(input, "responder_public_keys"));
                Assert.Equal((expected.GetProperty("accepted").GetBoolean(), expected.GetProperty("reason").GetString()), (r.Accepted, r.Reason));
                break;
            }
            case "verify_intent":
            {
                var r = OfflineVerifier.VerifyDataAccessIntent(input.GetProperty("intent").GetRawText(),
                    input.GetProperty("policy").GetRawText(), Strings(input, "agent_public_keys"),
                    OfflineVerifier.ParseTimestamp(input.GetProperty("at").GetString()!));
                Assert.Equal(expected.GetProperty("detail").GetString(), r.Violations.FirstOrDefault()?.Detail);
                break;
            }
            default:
                Assert.Fail($"unknown kind {v.GetProperty("kind").GetString()}");
                break;
        }
    }

    [Fact]
    public void NamesTimestampPathsAtAnyDepth()
    {
        var agreement = Vector("verify-agreement-signed-non-canonical-timestamp").GetProperty("input").GetProperty("agreement");
        Assert.Equal(new[] { "agreed_terms.valid_from" }, StrictFields.NonCanonicalTimestamps("AgreementRecord", agreement));
    }

    [Fact]
    public void FloatUnderflowIsZero() => Assert.Equal("[0.0]", Canonical.FromJson("[1e-400]"));

    [Fact]
    public void BytesMustBeUtf8AndAByteOrderMarkIsRefused()
    {
        Assert.Equal("invalid_json", Assert.Throws<StrictJsonException>(() => StrictJson.DecodeUtf8(new byte[] { 0x7b, 0xff, 0x7d })).Reason);
        var withMark = StrictJson.DecodeUtf8(new byte[] { 0xef, 0xbb, 0xbf, 0x7b, 0x7d });
        Assert.Equal("\ufeff{}", withMark);
        Assert.Equal("invalid_json", Assert.Throws<StrictJsonException>(() => StrictJson.Check(withMark)).Reason);
    }

    [Fact]
    public void ARefusalIsAJsonException()
    {
        JsonException e = Assert.Throws<StrictJsonException>(() => StrictJson.Check("{\"a\":1,\"a\":2}"));
        Assert.Equal("duplicate_key", ((StrictJsonException)e).Reason);
    }
}
