using System.Text.Json;
using GenesisMesh;
using Xunit;

namespace GenesisMesh.Sdk.Tests;

/// <summary>
/// Shared conformance vectors generated by the Python reference
/// (genesismesh/conformance/generate_vectors.py interop) and copied here unchanged.
/// Every vector must produce exactly the reference outcome.
/// </summary>
public class ConformanceTests
{
    private static readonly string VectorsPath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "interop.json");

    public static IEnumerable<object[]> VectorIds()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(VectorsPath));
        foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
            yield return new object[] { v.GetProperty("id").GetString()! };
    }

    private static JsonElement Vector(string id)
    {
        var doc = JsonDocument.Parse(File.ReadAllText(VectorsPath));
        return doc.RootElement.GetProperty("vectors").EnumerateArray().Single(v => v.GetProperty("id").GetString() == id);
    }

    private static List<string> Strings(JsonElement input, string key) =>
        input.GetProperty(key).EnumerateArray().Select(e => e.GetString()!).ToList();

    [Theory]
    [MemberData(nameof(VectorIds))]
    public void ReproducesTheReferenceOutcome(string id)
    {
        var v = Vector(id);
        var input = v.GetProperty("input");
        var expected = v.GetProperty("expected");
        switch (v.GetProperty("kind").GetString())
        {
            case "canonical_json":
                Assert.Equal(expected.GetProperty("canonical").GetString(), Canonical.FromJson(input.GetProperty("json").GetString()!));
                break;
            case "agreement":
            {
                var digest = input.TryGetProperty("expected_graph_digest", out var g) ? g.GetString() : null;
                var r = OfflineVerifier.VerifyAgreement(input.GetProperty("agreement").GetRawText(),
                    Strings(input, "offerer_public_keys"), Strings(input, "responder_public_keys"), digest);
                Assert.Equal(expected.GetProperty("accepted").GetBoolean(), r.Accepted);
                Assert.Equal(expected.GetProperty("reason").GetString(), r.Reason);
                break;
            }
            case "boundary_decision":
            {
                var options = new DecisionVerifyOptions
                {
                    OperatorPublicKeys = Strings(input, "operator_public_keys"),
                    Now = OfflineVerifier.ParseTimestamp(input.GetProperty("now").GetString()!),
                    ExpectedPolicies = input.TryGetProperty("expected_policies", out var ps)
                        ? ps.EnumerateArray().Select(p => p.GetRawText()).ToList() : null,
                    ExpectedAttestation = input.TryGetProperty("expected_attestation", out var a) ? a.GetRawText() : null,
                };
                var r = OfflineVerifier.VerifyBoundaryDecision(input.GetProperty("decision").GetRawText(), options);
                Assert.Equal(expected.GetProperty("accepted").GetBoolean(), r.Accepted);
                Assert.Equal(expected.GetProperty("reason").GetString(), r.Reason);
                Assert.Equal(expected.GetProperty("authorized").GetBoolean(), r.Authorized);
                break;
            }
            case "data_license_policy":
                Assert.Equal(expected.GetProperty("valid").GetBoolean(),
                    OfflineVerifier.VerifyDataLicensePolicySignature(input.GetProperty("policy").GetRawText(), Strings(input, "licensor_public_keys")));
                break;
            case "data_access_intent":
            {
                var r = OfflineVerifier.VerifyDataAccessIntent(input.GetProperty("intent").GetRawText(),
                    input.GetProperty("policy").GetRawText(), Strings(input, "agent_public_keys"),
                    OfflineVerifier.ParseTimestamp(input.GetProperty("at").GetString()!));
                Assert.Equal(expected.GetProperty("valid").GetBoolean(), r.Valid);
                var reason = expected.GetProperty("violation_reason");
                Assert.Equal(reason.ValueKind == JsonValueKind.Null ? null : reason.GetString(), r.ViolationReason);
                Assert.Equal(expected.GetProperty("violation_types").EnumerateArray().Select(e => e.GetString()!).ToList(),
                    r.Violations.Select(x => x.ViolationType).ToList());
                break;
            }
            default:
                Assert.Fail($"unknown vector kind {v.GetProperty("kind").GetString()}");
                break;
        }
    }

    [Fact]
    public void CoversEveryArtifactKind()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(VectorsPath));
        var kinds = doc.RootElement.GetProperty("vectors").EnumerateArray().Select(v => v.GetProperty("kind").GetString()).ToHashSet();
        foreach (var k in new[] { "canonical_json", "agreement", "boundary_decision", "data_license_policy", "data_access_intent" })
            Assert.Contains(k, kinds);
    }

    [Fact]
    public void AdminBodiesCanonicalizeLikePython()
    {
        var body = new Dictionary<string, object?> { ["z"] = "Zürich ✓ 😀", ["f"] = 0.25, ["big"] = 1e21, ["small"] = 0.00001, ["n"] = 42 };
        var canonical = System.Text.Encoding.UTF8.GetString(Auth.CanonicalJson(body));
        Assert.Equal("{\"big\":1e+21,\"f\":0.25,\"n\":42,\"small\":1e-05,\"z\":\"Z\\u00fcrich \\u2713 \\ud83d\\ude00\"}", canonical);
    }

    [Theory]
    [InlineData(1.0, "1.0")]
    [InlineData(90.0, "90.0")]
    [InlineData(0.0001, "0.0001")]
    [InlineData(0.00001, "1e-05")]
    [InlineData(1e16, "1e+16")]
    [InlineData(1.5e16, "1.5e+16")]
    [InlineData(123456789.5, "123456789.5")]
    [InlineData(-0.5, "-0.5")]
    [InlineData(1e15, "1000000000000000.0")]
    public void FloatsUsePythonRepr(double value, string expected) =>
        Assert.Equal(expected, Canonical.PythonFloatRepr(value));
}
