using System.Text.Json;
using System.Text.Json.Nodes;
using GenesisMesh;
using Xunit;

namespace GenesisMesh.Sdk.Tests;

/// <summary>
/// Shared conformance suite <c>field_registry</c> (v1.2.0), generated by the Python reference
/// (genesismesh/conformance/generate_vectors.py field_registry) and copied here unchanged: the field
/// registry of signed records and the fields every verifier refuses.
/// </summary>
public class FieldRegistryConformanceTests
{
    private static readonly string SuitePath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "field_registry.json");
    private static readonly string InteropPath = Path.Combine(AppContext.BaseDirectory, "testdata", "conformance", "interop.json");

    private static JsonElement Suite() => JsonDocument.Parse(File.ReadAllText(SuitePath)).RootElement;

    private static JsonElement Vector(string id) =>
        Suite().GetProperty("vectors").EnumerateArray().Single(x => x.GetProperty("id").GetString() == id);

    public static IEnumerable<object[]> VectorIds() =>
        Suite().GetProperty("vectors").EnumerateArray().Select(v => new object[] { v.GetProperty("id").GetString()! });

    [Fact]
    public void EmbedsTheRegistryOfTheSuite()
    {
        var suite = JsonNode.Parse(Suite().GetProperty("registry").GetRawText());
        var embedded = JsonNode.Parse(StrictFields.RegistryJson);
        Assert.True(JsonNode.DeepEquals(suite, embedded),
            "canonical_registry.json differs from the suite: run `python scripts/sync_canonical_registry.py`");
    }

    [Fact]
    public void KeepsThisSdksCanonicalRulesEqualToTheRegistrys()
    {
        Assert.Equal(OfflineVerifier.DecisionOmittedWhenAbsent, StrictFields.Model("BoundaryDecision").OmitWhenNone);
        Assert.Equal(OfflineVerifier.AgreementCanonicalKeys, StrictFields.Model("AgreementRecord").CanonicalFields);
    }

    [Fact]
    public void HasEnoughVectors() => Assert.True(VectorIds().Count() >= 70);

    [Theory]
    [MemberData(nameof(VectorIds))]
    public void ReproducesTheReferenceOutcome(string id)
    {
        var v = Vector(id);
        var expected = v.GetProperty("expected");
        switch (v.GetProperty("kind").GetString())
        {
            case "unknown_fields":
                var want = expected.GetProperty("unknown_fields").EnumerateArray().Select(e => e.GetString()!).ToList();
                Assert.Equal(want, StrictFields.UnknownFields(v.GetProperty("model").GetString()!, v.GetProperty("record")));
                break;
            case "verify_decision":
            {
                var input = v.GetProperty("input");
                var r = OfflineVerifier.VerifyBoundaryDecision(input.GetProperty("decision").GetRawText(), new DecisionVerifyOptions
                {
                    OperatorPublicKeys = Strings(input, "operator_public_keys"),
                    Now = OfflineVerifier.ParseTimestamp(input.GetProperty("now").GetString()!),
                });
                Assert.Equal((expected.GetProperty("accepted").GetBoolean(), expected.GetProperty("reason").GetString()), (r.Accepted, r.Reason));
                break;
            }
            case "verify_agreement":
            {
                var input = v.GetProperty("input");
                var r = OfflineVerifier.VerifyAgreement(input.GetProperty("agreement").GetRawText(),
                    Strings(input, "offerer_public_keys"), Strings(input, "responder_public_keys"));
                Assert.Equal((expected.GetProperty("accepted").GetBoolean(), expected.GetProperty("reason").GetString()), (r.Accepted, r.Reason));
                break;
            }
            case "entry_kind":
            case "export":
                // This SDK has no evidence export verifier.
                break;
            default:
                Assert.Fail($"unknown kind {v.GetProperty("kind").GetString()}");
                break;
        }
    }

    private static JsonElement Input(string id) =>
        JsonDocument.Parse(File.ReadAllText(InteropPath)).RootElement.GetProperty("vectors").EnumerateArray()
            .Single(v => v.GetProperty("id").GetString() == id).GetProperty("input");

    private static string WithField(JsonElement record, string key)
    {
        var node = JsonNode.Parse(record.GetRawText())!.AsObject();
        node[key] = "x";
        return node.ToJsonString();
    }

    private static List<string> Strings(JsonElement input, string key) =>
        input.GetProperty(key).EnumerateArray().Select(e => e.GetString()!).ToList();

    [Fact]
    public void AnExpectedPolicyWithAnUnknownFieldIsRefusedByName()
    {
        var newer = Vector("verify-decision-newer-signed-field").GetProperty("input");
        var r = OfflineVerifier.VerifyBoundaryDecision(newer.GetProperty("decision").GetRawText(), new DecisionVerifyOptions
        {
            OperatorPublicKeys = Strings(newer, "operator_public_keys"),
            Now = OfflineVerifier.ParseTimestamp(newer.GetProperty("now").GetString()!),
            ExpectedPolicies = new[] { Vector("boundarypolicy-top").GetProperty("record").GetRawText() },
        });
        Assert.Equal("unknown_field", r.Reason);
    }

    [Fact]
    public void AFieldOutsideTheSignatureFailsTheSignature()
    {
        var bd = Input("bd-003");
        var options = new DecisionVerifyOptions
        {
            OperatorPublicKeys = Strings(bd, "operator_public_keys"),
            Now = OfflineVerifier.ParseTimestamp(bd.GetProperty("now").GetString()!),
        };
        Assert.Equal("authorized", OfflineVerifier.VerifyBoundaryDecision(bd.GetProperty("decision").GetRawText(), options).Reason);
        var added = OfflineVerifier.VerifyBoundaryDecision(WithField(bd.GetProperty("decision"), "risk_tier"), options);
        Assert.False(added.Accepted);
        Assert.Equal("invalid_signature", added.Reason);

        var agr = Input("agr-001");
        Assert.True(OfflineVerifier.VerifyAgreement(WithField(agr.GetProperty("agreement"), "x"),
            Strings(agr, "offerer_public_keys"), Strings(agr, "responder_public_keys")).Accepted);

        var pol = Input("pol-001");
        Assert.False(OfflineVerifier.VerifyDataLicensePolicySignature(WithField(pol.GetProperty("policy"), "x"),
            Strings(pol, "licensor_public_keys")));

        var intent = Input("int-001");
        var at = OfflineVerifier.ParseTimestamp(intent.GetProperty("at").GetString()!);
        var unsigned = OfflineVerifier.VerifyDataAccessIntent(WithField(intent.GetProperty("intent"), "x"),
            intent.GetProperty("policy").GetRawText(), Strings(intent, "agent_public_keys"), at);
        Assert.False(unsigned.Valid);
        Assert.Equal("Invalid intent signature", Assert.Single(unsigned.Violations).Detail);
        var policy = OfflineVerifier.VerifyDataAccessIntent(intent.GetProperty("intent").GetRawText(),
            WithField(intent.GetProperty("policy"), "x"), Strings(intent, "agent_public_keys"), at);
        Assert.False(policy.Valid);
        Assert.Equal("Unknown field: policy.x", Assert.Single(policy.Violations).Detail);
    }
}
